# Generated by Django 6.0.6 on 2026-07-23 16:45

import snapadmin.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='last_seen',
            field=snapadmin.fields.SnapDateTimeField(blank=True, null=True, verbose_name='Last Seen In Feed'),
        ),
    ]
