# Generated by Django 6.0.6 on 2026-09-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_exchangerate_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tenant_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Row-level tenant isolation key — see SnapModel.tenant_scoped.",
                max_length=64,
                null=True,
                verbose_name="Tenant",
            ),
        ),
    ]
