# Generated by Django 6.0.6 on 2026-09-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_order_tenant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyStockLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(db_index=True, max_length=64, verbose_name="SKU"),
                ),
                (
                    "warehouse",
                    models.CharField(max_length=64, verbose_name="Warehouse"),
                ),
                ("on_hand", models.IntegerField(default=0, verbose_name="On Hand")),
                (
                    "reorder_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Reorder Cost",
                    ),
                ),
                (
                    "counted_at",
                    models.DateTimeField(auto_now=True, verbose_name="Counted At"),
                ),
            ],
            options={
                "verbose_name": "Legacy Stock Level",
                "verbose_name_plural": "Legacy Stock Levels",
                "permissions": [("view_stock_cost", "Can view stock reorder cost")],
            },
        ),
    ]
