# Generated by Django 6.0.6 on 2026-09-12 17:57

import snapadmin.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_legacystocklevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='tax_id',
            field=snapadmin.fields.SnapEncryptedCharField(blank=True, blind_index=True, max_length=32, null=True, verbose_name='Tax ID'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='tax_id_bi',
            field=snapadmin.fields.SnapBlindIndexField(blank=True, db_index=True, editable=False, max_length=43, null=True, source_field='tax_id'),
        ),
    ]
