# Generated by Django 6.0.6 on 2026-09-13 22:17

import snapadmin.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_customerprofile_tax_id_customerprofile_tax_id_bi'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='delete_at',
            field=snapadmin.fields.SnapDateTimeField(blank=True, null=True, verbose_name='Delete At'),
        ),
    ]
