"""Tests for :mod:`snapadmin.quickstart.wizard` (#CLI3e)."""

from __future__ import annotations

import pytest

from snapadmin.quickstart import wizard


def _inputs(values):
    iterator = iter(values)
    return lambda prompt="": next(iterator)


class TestChoose:
    def test_valid_choice(self):
        assert wizard._choose(_inputs(["2"]), "L", [("1", "a"), ("2", "b")], "1") == "b"

    def test_invalid_falls_back_to_default(self):
        assert wizard._choose(_inputs(["9"]), "L", [("1", "a"), ("2", "b")], "1") == "a"

    def test_empty_uses_default(self):
        assert wizard._choose(_inputs([""]), "L", [("1", "a"), ("2", "b")], "2") == "b"


class TestYesNo:
    def test_empty_returns_default_true(self):
        assert wizard._yes_no(_inputs([""]), "q", True) is True

    def test_empty_returns_default_false(self):
        assert wizard._yes_no(_inputs([""]), "q", False) is False

    def test_yes(self):
        assert wizard._yes_no(_inputs(["Y"]), "q", False) is True

    def test_no(self):
        assert wizard._yes_no(_inputs(["n"]), "q", True) is False


class TestTruthy:
    @pytest.mark.parametrize(
        "value,expected",
        [(True, True), (False, False), ("true", True), ("False", False), ("1", True), ("no", False)],
    )
    def test_truthy(self, value, expected):
        assert wizard._truthy(value) is expected


class TestRunWizard:
    def test_runserver_sqlite(self):
        config = wizard.run_wizard(input_fn=_inputs(["1", "1", "n", "y", "n"]), getpass_fn=_inputs(["pw"]))
        assert config["mode"] == "runserver"
        assert config["database"] == "sqlite"
        assert config["elasticsearch"] is False
        assert config["admin_password"] == "pw"
        assert config["generate_secret_key"] is True
        assert config["debug"] is False

    def test_runserver_postgres_defaults(self):
        config = wizard.run_wizard(
            input_fn=_inputs(["1", "2", "", "", "", "", "y", "", ""]),
            getpass_fn=_inputs(["", ""]),
        )
        assert config["database"] == "postgresql"
        assert config["db_host"] == "localhost"
        assert config["db_password"] == "snapadmin"  # empty → default
        assert config["admin_password"] == "admin"  # empty → default
        assert config["elasticsearch"] is True

    def test_docker_mode(self):
        config = wizard.run_wizard(input_fn=_inputs(["2", "y", "n", "y"]), getpass_fn=_inputs(["x"]))
        assert config["mode"] == "docker"
        assert config["database"] == "postgresql"
        assert config["debug"] is True
        assert config["generate_secret_key"] is False


class TestEnvLines:
    def test_sqlite_generated_key(self):
        text = "\n".join(wizard.env_lines({"database": "sqlite", "generate_secret_key": True, "debug": False}))
        assert "SECRET_KEY=" in text and "change-me" not in text
        assert "POSTGRES_HOST=\n" in text + "\n"  # empty host → SQLite fallback
        assert "DEBUG=False" in text
        assert "ELASTICSEARCH_ENABLED=False" in text

    def test_postgres_no_key_with_admin(self):
        text = "\n".join(
            wizard.env_lines(
                {
                    "database": "postgresql",
                    "db_host": "h",
                    "db_port": "1",
                    "db_user": "u",
                    "db_password": "p",
                    "db_name": "n",
                    "generate_secret_key": False,
                    "elasticsearch": True,
                    "admin_password": "secret",
                    "debug": True,
                }
            )
        )
        assert "SECRET_KEY=change-me-insecure-demo-key" in text
        assert "POSTGRES_HOST=h" in text
        assert "POSTGRES_PASSWORD=p" in text
        assert "ELASTICSEARCH_ENABLED=True" in text
        assert "SNAPADMIN_SEED_ADMIN_PASSWORD=secret" in text
        assert "DEBUG=True" in text

    def test_string_boolean_from_config_file(self):
        text = "\n".join(wizard.env_lines({"database": "sqlite", "generate_secret_key": "false"}))
        assert "SECRET_KEY=change-me-insecure-demo-key" in text


class TestWriteEnv:
    def test_writes_file(self, tmp_path):
        path = wizard.write_env({"database": "sqlite"}, tmp_path / ".env")
        assert path.read_text().startswith("# Generated by snapadmin-demo")
