"""
Interactive configuration wizard for ``snapadmin-demo`` and the ``.env`` writer.

Prompts (in English) for a run mode, database, admin password, secret-key generation and debug flag,
then writes a ``.env`` the demo project reads. The demo supports SQLite (default) or PostgreSQL and a
Docker stack — **not MySQL** — so those are the only options offered, matching what the demo can
actually run. ``input_fn`` / ``getpass_fn`` are injected so the prompts are testable without a TTY.
"""

from __future__ import annotations

import getpass
import secrets
from pathlib import Path
from typing import Callable


def _truthy(value: object) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "1", "yes", "y"}


def _choose(input_fn: Callable[[str], str], label: str, options: list[tuple[str, str]], default: str) -> str:
    print(f"{label}:")
    for key, value in options:
        print(f"  [{key}] {value}")
    choice = input_fn(f"  > [{default}]: ").strip() or default
    mapping = dict(options)
    return mapping.get(choice, mapping[default])


def _yes_no(input_fn: Callable[[str], str], question: str, default: bool) -> bool:
    answer = input_fn(f"{question} [{'Y/n' if default else 'y/N'}]: ").strip().lower()
    if not answer:
        return default
    return answer in {"y", "yes"}


def run_wizard(
    *,
    input_fn: Callable[[str], str] = input,
    getpass_fn: Callable[[str], str] = getpass.getpass,
) -> dict:
    """Collect a demo configuration interactively."""
    print("🚀 SnapAdmin Demo Configuration Wizard\n")
    config: dict = {"mode": _choose(input_fn, "Run mode", [("1", "runserver"), ("2", "docker")], "1")}

    if config["mode"] == "runserver":
        config["database"] = _choose(
            input_fn, "Database", [("1", "sqlite"), ("2", "postgresql")], "1"
        )
        if config["database"] == "postgresql":
            config["db_host"] = input_fn("  Host [localhost]: ").strip() or "localhost"
            config["db_port"] = input_fn("  Port [5432]: ").strip() or "5432"
            config["db_user"] = input_fn("  Username [snapadmin]: ").strip() or "snapadmin"
            config["db_password"] = getpass_fn("  Password: ") or "snapadmin"
            config["db_name"] = input_fn("  Database [snapadmin]: ").strip() or "snapadmin"
    else:
        config["database"] = "postgresql"  # the Docker stack uses PostgreSQL

    config["elasticsearch"] = _yes_no(input_fn, "Enable Elasticsearch (full-text search)?", False)
    config["admin_password"] = getpass_fn("Admin password [admin]: ") or "admin"
    config["generate_secret_key"] = _yes_no(input_fn, "Generate a secret key automatically?", True)
    config["debug"] = _yes_no(input_fn, "Enable debug mode?", False)
    return config


def env_lines(config: dict) -> list[str]:
    """The ``.env`` lines for ``config`` (only the variables the demo actually reads)."""
    lines = ["# Generated by snapadmin-demo"]
    if _truthy(config.get("generate_secret_key", True)):
        lines.append(f"SECRET_KEY={secrets.token_urlsafe(50)}")
    else:
        lines.append("SECRET_KEY=change-me-insecure-demo-key")
    lines.append(f"DEBUG={'True' if _truthy(config.get('debug', False)) else 'False'}")

    if config.get("database") == "postgresql":
        lines.append(f"POSTGRES_HOST={config.get('db_host', 'localhost')}")
        lines.append(f"POSTGRES_PORT={config.get('db_port', '5432')}")
        lines.append(f"POSTGRES_USER={config.get('db_user', 'snapadmin')}")
        lines.append(f"POSTGRES_PASSWORD={config.get('db_password', 'snapadmin')}")
        lines.append(f"POSTGRES_DB={config.get('db_name', 'snapadmin')}")
    else:
        lines.append("POSTGRES_HOST=")  # empty → the demo falls back to SQLite

    lines.append(f"ELASTICSEARCH_ENABLED={'True' if _truthy(config.get('elasticsearch', False)) else 'False'}")
    if config.get("admin_password"):
        lines.append(f"SNAPADMIN_SEED_ADMIN_PASSWORD={config['admin_password']}")
    return lines


def write_env(config: dict, dest: Path) -> Path:
    """Write ``config`` to a ``.env`` file at ``dest`` and return the path."""
    dest = Path(dest)
    dest.write_text("\n".join(env_lines(config)) + "\n")
    return dest
