# Generated by Django 6.0.6 on 2026-07-05 21:05

import django.db.models.deletion
import snapadmin.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exception_class",
                    models.CharField(
                        help_text="Exception class name, or HTTP<code> for a 5xx response without an exception.",
                        max_length=255,
                        verbose_name="Exception",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "path",
                    models.CharField(blank=True, max_length=500, verbose_name="Path"),
                ),
                (
                    "method",
                    models.CharField(blank=True, max_length=10, verbose_name="Method"),
                ),
                (
                    "status_code",
                    models.PositiveIntegerField(
                        default=500, verbose_name="Status Code"
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 of exception class + path — groups repeats of the same error.",
                        max_length=64,
                        verbose_name="Fingerprint",
                    ),
                ),
                ("traceback", models.TextField(blank=True, verbose_name="Traceback")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Occurred At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Event",
                "verbose_name_plural": "Error Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_name",
                    models.CharField(
                        help_text="A descriptive name for this token (e.g. 'CI Pipeline', 'Read-only dashboard').",
                        max_length=100,
                        verbose_name="Token Name",
                    ),
                ),
                (
                    "token_prefix",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="First 8 characters of the key, for identification. Not secret.",
                        max_length=8,
                        verbose_name="Token Prefix",
                    ),
                ),
                (
                    "token_digest",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="SHA-256 hash of the secret key. The raw key is never stored — it is shown only once, at creation.",
                        max_length=64,
                        unique=True,
                        verbose_name="Token Digest",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank for a token that never expires.",
                        null=True,
                        verbose_name="Expiration Date",
                    ),
                ),
                (
                    "allowed_models",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of 'app_label.ModelName' strings this token can access.",
                        validators=[snapadmin.models.validate_allowed_models],
                        verbose_name="Allowed Models",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive tokens are rejected without being deleted.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Used At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Token",
                "verbose_name_plural": "API Tokens",
                "ordering": ["-created_at"],
                "permissions": [("view_raw_pii", "Can view unmasked PII data")],
            },
        ),
        migrations.CreateModel(
            name="SnapadminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Action",
                    ),
                ),
                (
                    "actor_repr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Actor (snapshot)"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "app_label",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="App Label",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="Model"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Object ID"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(blank=True, max_length=255, verbose_name="Object"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="Before/after field diff, if any.",
                        null=True,
                        verbose_name="Changes",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Timestamp"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SnapExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "app_label",
                    models.CharField(max_length=100, verbose_name="App Label"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                (
                    "export_format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("json", "JSON")],
                        default="csv",
                        max_length=8,
                        verbose_name="Format",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="ORM field=value filters applied to the export queryset.",
                        verbose_name="Filters",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(default=0, verbose_name="Total Rows"),
                ),
                (
                    "processed_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Processed Rows"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="File Name"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Error")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished At"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Job",
                "verbose_name_plural": "Export Jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
