# Generated by Django 6.0.6 on 2026-06-23 19:35

import django.db.models.deletion
import snapadmin.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(help_text="A descriptive name for this token (e.g. 'CI Pipeline', 'Read-only dashboard').", max_length=100, verbose_name='Token Name')),
                ('token_key', models.CharField(default=snapadmin.models._generate_token_key, help_text='Secret 40-character key. Treat like a password.', max_length=40, unique=True, verbose_name='Token Key')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Leave blank for a token that never expires.', null=True, verbose_name='Expiration Date')),
                ('allowed_models', models.JSONField(blank=True, default=list, help_text="List of 'app_label.ModelName' strings this token can access.", validators=[snapadmin.models.validate_allowed_models], verbose_name='Allowed Models')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tokens are rejected without being deleted.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
