# Generated by Django 6.0.6 on 2026-07-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapexportjob',
            name='cursor_bytes',
            field=models.PositiveBigIntegerField(default=0, help_text='Byte length of the working file confirmed at cursor_pk.', verbose_name='Resume Byte Offset'),
        ),
        migrations.AddField(
            model_name='snapexportjob',
            name='cursor_pk',
            field=models.CharField(blank=True, default='', help_text='Primary key of the last exported row; blank means start from the beginning.', max_length=255, verbose_name='Resume Cursor (PK)'),
        ),
        migrations.AlterField(
            model_name='snapexportjob',
            name='processed_rows',
            field=models.PositiveIntegerField(default=0, help_text='Rows written so far — drives progress-percent and ETA reporting.', verbose_name='Processed Rows'),
        ),
    ]
