# Generated by Django 6.0.6 on 2026-07-18 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "snapadmin",
            "0002_snapexportjob_cursor_bytes_snapexportjob_cursor_pk_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapReindexJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "app_label",
                    models.CharField(max_length=100, verbose_name="App Label"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(default=0, verbose_name="Total Rows"),
                ),
                (
                    "processed_rows",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Rows written so far — drives progress-percent and ETA reporting.",
                        verbose_name="Processed Rows",
                    ),
                ),
                (
                    "cursor_pk",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Primary key of the last indexed row; blank means start from the beginning.",
                        max_length=255,
                        verbose_name="Resume Cursor (PK)",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Error")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reindex Job",
                "verbose_name_plural": "Reindex Jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
