# Generated by Django 6.0.6 on 2026-07-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapadmin', '0002_hash_api_token_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_class', models.CharField(help_text='Exception class name, or HTTP<code> for a 5xx response without an exception.', max_length=255, verbose_name='Exception')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='Path')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='Method')),
                ('status_code', models.PositiveIntegerField(default=500, verbose_name='Status Code')),
                ('fingerprint', models.CharField(blank=True, db_index=True, help_text='SHA-256 of exception class + path — groups repeats of the same error.', max_length=64, verbose_name='Fingerprint')),
                ('traceback', models.TextField(blank=True, verbose_name='Traceback')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Occurred At')),
            ],
            options={
                'verbose_name': 'Error Event',
                'verbose_name_plural': 'Error Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
