# Generated by Django 6.0.6 on 2026-07-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapadmin', '0003_errorevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apitoken',
            options={'ordering': ['-created_at'], 'permissions': [('view_raw_pii', 'Can view unmasked PII data')], 'verbose_name': 'API Token', 'verbose_name_plural': 'API Tokens'},
        ),
    ]
