# Generated by Django 6.0.6 on 2026-07-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapadmin', '0003_snapreindexjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapexportjob',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Registered SNAPADMIN_EXPORT_SOURCES name; blank uses the default ORM source.', max_length=64, verbose_name='Row Source'),
        ),
    ]
