# Generated by Django 6.0.6 on 2026-08-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the ``xlsx`` choice to ``SnapExportJob.export_format``.

    Choices live in Python, not in the database: ``sqlmigrate`` reports this
    operation as a no-op on every backend (same column type, same ``max_length``).
    It exists only to keep ``makemigrations --check`` clean, and applying it
    neither locks nor rewrites the table.
    """

    dependencies = [
        ('snapadmin', '0004_snapexportjob_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapexportjob',
            name='export_format',
            field=models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('xlsx', 'XLSX')], default='csv', max_length=8, verbose_name='Format'),
        ),
    ]
