# Generated by Django 6.0.6 on 2026-07-04 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('snapadmin', '0004_alter_apitoken_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapadminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], db_index=True, max_length=16, verbose_name='Action')),
                ('actor_repr', models.CharField(blank=True, max_length=255, verbose_name='Actor (snapshot)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('app_label', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='App Label')),
                ('model', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Model')),
                ('object_id', models.CharField(blank=True, max_length=255, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Object')),
                ('changes', models.JSONField(blank=True, help_text='Before/after field diff, if any.', null=True, verbose_name='Changes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
