# Generated by Django 6.0.6 on 2026-08-30 18:55

import snapadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapadmin", "0005_alter_snapexportjob_export_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="allowed_scopes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Free-form strings a project's own views may check with token_has_scope() — SnapAdmin stores and exposes them, the meaning is the project's. Empty denies every scope check (fail-closed), unlike an empty Allowed Models.",
                validators=[snapadmin.models.validate_allowed_scopes],
                verbose_name="Allowed Scopes",
            ),
        ),
    ]
