# Generated by Django 6.0.6 on 2026-07-04 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapadmin', '0005_snapadminauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100, verbose_name='App Label')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], default='csv', max_length=8, verbose_name='Format')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='ORM field=value filters applied to the export queryset.', verbose_name='Filters')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Total Rows')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='Processed Rows')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='File Name')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
