# Generated by Django 6.0.6 on 2026-09-01 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapadmin", "0006_apitoken_allowed_scopes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "app_label",
                    models.CharField(max_length=100, verbose_name="App Label"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(default=0, verbose_name="Total Rows"),
                ),
                (
                    "processed_rows",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Rows written so far — drives progress-percent and ETA reporting.",
                        verbose_name="Processed Rows",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Error")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished At"
                    ),
                ),
                (
                    "import_format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("json", "JSON")],
                        default="csv",
                        max_length=8,
                        verbose_name="Format",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True,
                        help_text="Display-only name of the input file this job reads.",
                        max_length=255,
                        verbose_name="Source File",
                    ),
                ),
                (
                    "column_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Explicit CSV/JSON header -> field name overrides; header-name matching fills the rest.",
                        verbose_name="Column Map",
                    ),
                ),
                (
                    "natural_key",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Field name(s) that identify a duplicate row; blank resolves the default at run time.",
                        verbose_name="Natural Key",
                    ),
                ),
                (
                    "on_conflict",
                    models.CharField(
                        choices=[
                            ("fail", "Fail"),
                            ("skip", "Skip"),
                            ("update", "Update"),
                        ],
                        default="fail",
                        max_length=8,
                        verbose_name="On Conflict",
                    ),
                ),
                (
                    "report_file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Report File"
                    ),
                ),
                (
                    "report_cursor_bytes",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Byte length of the report file confirmed as written.",
                        verbose_name="Report Resume Byte Offset",
                    ),
                ),
                (
                    "created_count",
                    models.PositiveIntegerField(default=0, verbose_name="Created"),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(default=0, verbose_name="Updated"),
                ),
                (
                    "skipped_count",
                    models.PositiveIntegerField(default=0, verbose_name="Skipped"),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(default=0, verbose_name="Failed"),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Used for PII-access checks on masked target fields; blank is treated as no PII access.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Job",
                "verbose_name_plural": "Import Jobs",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
