# Generated by Django 6.0.6 on 2026-09-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapadmin", "0007_snapimportjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapexportjob",
            name="tenant_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="The submitter's tenant, replayed when the job runs. Blank for a job whose target model is not tenant-scoped.",
                max_length=64,
                verbose_name="Tenant",
            ),
        ),
        migrations.AddField(
            model_name="snapimportjob",
            name="tenant_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="The submitter's tenant, replayed when the job runs. Blank for a job whose target model is not tenant-scoped.",
                max_length=64,
                verbose_name="Tenant",
            ),
        ),
        migrations.AddField(
            model_name="snapreindexjob",
            name="tenant_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="The submitter's tenant, replayed when the job runs. Blank for a job whose target model is not tenant-scoped.",
                max_length=64,
                verbose_name="Tenant",
            ),
        ),
    ]
