# Generated by Django 6.0.6 on 2026-07-05 21:05

import django.db.models.deletion
import snapadmin.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extra_settings", "0008_auto_20221024_0717"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    snapadmin.fields.SnapCharField(
                        blank=True, max_length=255, null=True, verbose_name="Query"
                    ),
                ),
                (
                    "results_count",
                    snapadmin.fields.SnapIntegerField(
                        blank=True, null=True, verbose_name="Results Count"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
            ],
            options={
                "verbose_name": "Search Log",
                "verbose_name_plural": "Search Logs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    snapadmin.fields.SnapCharField(
                        blank=True, max_length=100, null=True, verbose_name="Action"
                    ),
                ),
                (
                    "user_email",
                    snapadmin.fields.SnapEmailField(
                        blank=True, max_length=254, null=True, verbose_name="User Email"
                    ),
                ),
                (
                    "created_at",
                    snapadmin.fields.SnapDateTimeField(
                        auto_now_add=True,
                        blank=True,
                        null=True,
                        verbose_name="Created At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    snapadmin.fields.SnapCharField(
                        blank=True, max_length=100, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "slug",
                    snapadmin.fields.SnapSlugField(
                        blank=True, null=True, verbose_name="Slug"
                    ),
                ),
                (
                    "is_active",
                    snapadmin.fields.SnapBooleanField(
                        blank=True, default=True, null=True, verbose_name="Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    snapadmin.fields.SnapCharField(
                        blank=True, max_length=100, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    snapadmin.fields.SnapCharField(
                        blank=True, max_length=100, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "origin",
                    snapadmin.fields.SnapCharField(
                        blank=True,
                        choices=[
                            ("status_a", "Status A"),
                            ("status_b", "Status B"),
                            ("status_c", "Status C"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Origin",
                    ),
                ),
                (
                    "email",
                    snapadmin.fields.SnapEmailField(
                        blank=True, max_length=200, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "active",
                    snapadmin.fields.SnapBooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    snapadmin.fields.SnapCharField(
                        blank=False,
                        max_length=3,
                        null=False,
                        unique=True,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "base",
                    snapadmin.fields.SnapCharField(
                        blank=True,
                        default="EUR",
                        max_length=3,
                        null=True,
                        verbose_name="Base",
                    ),
                ),
                (
                    "rate",
                    snapadmin.fields.SnapDecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="Rate",
                    ),
                ),
                (
                    "synced_at",
                    snapadmin.fields.SnapDateTimeField(
                        auto_now=True, blank=True, null=True, verbose_name="Last Synced"
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
            },
        ),
        migrations.CreateModel(
            name="Showcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char_field",
                    snapadmin.fields.SnapCharField(
                        blank=True, max_length=100, null=True, verbose_name="Char Field"
                    ),
                ),
                (
                    "text_field",
                    snapadmin.fields.SnapTextField(
                        blank=True, null=True, verbose_name="Text Field"
                    ),
                ),
                (
                    "wysiwyg_field",
                    snapadmin.fields.SnapTextField(
                        blank=True, null=True, verbose_name="WYSIWYG Field"
                    ),
                ),
                (
                    "integer_field",
                    snapadmin.fields.SnapIntegerField(
                        blank=True, null=True, verbose_name="Integer Field"
                    ),
                ),
                (
                    "positive_integer",
                    snapadmin.fields.SnapPositiveIntegerField(
                        blank=True, null=True, verbose_name="Positive Int"
                    ),
                ),
                (
                    "float_field",
                    snapadmin.fields.SnapFloatField(
                        blank=True, null=True, verbose_name="Float Field"
                    ),
                ),
                (
                    "decimal_field",
                    snapadmin.fields.SnapDecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Decimal Field",
                    ),
                ),
                (
                    "big_int",
                    snapadmin.fields.SnapBigIntegerField(
                        blank=True, null=True, verbose_name="Big Int"
                    ),
                ),
                (
                    "date_field",
                    snapadmin.fields.SnapDateField(
                        blank=True, null=True, verbose_name="Date Field"
                    ),
                ),
                (
                    "datetime_field",
                    snapadmin.fields.SnapDateTimeField(
                        blank=True, null=True, verbose_name="DateTime Field"
                    ),
                ),
                (
                    "time_field",
                    snapadmin.fields.SnapTimeField(
                        blank=True, null=True, verbose_name="Time Field"
                    ),
                ),
                (
                    "duration_field",
                    snapadmin.fields.SnapDurationField(
                        blank=True, null=True, verbose_name="Duration Field"
                    ),
                ),
                (
                    "email_field",
                    snapadmin.fields.SnapEmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email Field",
                    ),
                ),
                (
                    "slug_field",
                    snapadmin.fields.SnapSlugField(
                        blank=True, null=True, verbose_name="Slug Field"
                    ),
                ),
                (
                    "url_field",
                    snapadmin.fields.SnapURLField(
                        blank=True, null=True, verbose_name="URL Field"
                    ),
                ),
                (
                    "uuid_field",
                    snapadmin.fields.SnapUUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        verbose_name="UUID Field",
                    ),
                ),
                (
                    "ip_field",
                    snapadmin.fields.SnapGenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "image_field",
                    snapadmin.fields.SnapImageField(
                        blank=True,
                        null=True,
                        upload_to="showcase/images/",
                        verbose_name="Image Field",
                    ),
                ),
                (
                    "file_field",
                    snapadmin.fields.SnapFileField(
                        blank=True,
                        null=True,
                        upload_to="showcase/files/",
                        verbose_name="File Field",
                    ),
                ),
                (
                    "boolean_field",
                    snapadmin.fields.SnapBooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Boolean Field",
                    ),
                ),
                (
                    "json_field",
                    snapadmin.fields.SnapJSONField(
                        blank=True, default=dict, null=True, verbose_name="JSON Field"
                    ),
                ),
                (
                    "rich_text_field",
                    snapadmin.fields.SnapRichTextField(
                        blank=True, null=True, verbose_name="Rich Text"
                    ),
                ),
                (
                    "phone_field",
                    snapadmin.fields.SnapPhoneField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "color_field",
                    snapadmin.fields.SnapColorField(
                        blank=True,
                        default="#3B82F6",
                        max_length=7,
                        null=True,
                        verbose_name="Color",
                    ),
                ),
                (
                    "small_int_field",
                    snapadmin.fields.SnapSmallIntegerField(
                        blank=True, null=True, verbose_name="Small Integer"
                    ),
                ),
                (
                    "pos_small_int_field",
                    snapadmin.fields.SnapPositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pos. Small Integer"
                    ),
                ),
                (
                    "pos_big_int_field",
                    snapadmin.fields.SnapPositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Pos. Big Integer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Showcase",
                "verbose_name_plural": "Showcase",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    snapadmin.fields.SnapCharField(
                        blank=True, max_length=50, null=True, verbose_name="Tag Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("extra_settings.setting",),
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "newsletter",
                    snapadmin.fields.SnapBooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Newsletter Opt-in",
                    ),
                ),
                (
                    "bio",
                    snapadmin.fields.SnapTextField(
                        blank=True, null=True, verbose_name="Bio"
                    ),
                ),
                (
                    "customer",
                    snapadmin.fields.SnapOneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="demo.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Profile",
                "verbose_name_plural": "Customer Profiles",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total",
                    snapadmin.fields.SnapDecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total",
                    ),
                ),
                (
                    "created_at",
                    snapadmin.fields.SnapDateTimeField(
                        auto_now_add=True,
                        blank=True,
                        null=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "customer",
                    snapadmin.fields.SnapForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="demo.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    snapadmin.fields.SnapCharField(
                        blank=True, max_length=200, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "price",
                    snapadmin.fields.SnapDecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                (
                    "available",
                    snapadmin.fields.SnapBooleanField(
                        blank=True, default=True, null=True, verbose_name="Available"
                    ),
                ),
                (
                    "description",
                    snapadmin.fields.SnapTextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "category",
                    snapadmin.fields.SnapForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="demo.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "tags",
                    snapadmin.fields.SnapManyToManyField(
                        blank=True, null=False, to="demo.tag", verbose_name="Tags"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    snapadmin.fields.SnapPositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="Quantity"
                    ),
                ),
                (
                    "price",
                    snapadmin.fields.SnapDecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Price at purchase",
                    ),
                ),
                (
                    "order",
                    snapadmin.fields.SnapForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="demo.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "product",
                    snapadmin.fields.SnapForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demo.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
    ]
