# Generated by Django 6.0.6 on 2026-06-23 19:45

import snapadmin.fields
import snapadmin.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='file_field',
            field=snapadmin.fields.SnapFileField(blank=True, null=True, upload_to='showcase/files/', validators=[snapadmin.validators.SnapFileValidator(allowed_encodings=None, allowed_extensions=None, max_size_bytes=None), snapadmin.validators.SnapFileValidator(allowed_encodings=None, allowed_extensions=None, max_size_bytes=None)], verbose_name='File Field'),
        ),
    ]
