# Generated by Django 6.0.6 on 2026-06-23 19:50

import snapadmin.fields
import snapadmin.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_showcase_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='color_field',
            field=snapadmin.fields.SnapColorField(blank=True, default='#3B82F6', max_length=7, null=True, validators=[snapadmin.validators.SnapColorValidator(), snapadmin.validators.SnapColorValidator()], verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='phone_field',
            field=snapadmin.fields.SnapPhoneField(blank=True, max_length=20, null=True, validators=[snapadmin.validators.SnapPhoneValidator(), snapadmin.validators.SnapPhoneValidator()], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='pos_big_int_field',
            field=snapadmin.fields.SnapPositiveBigIntegerField(blank=True, null=True, verbose_name='Pos. Big Integer'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='pos_small_int_field',
            field=snapadmin.fields.SnapPositiveSmallIntegerField(blank=True, null=True, verbose_name='Pos. Small Integer'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='rich_text_field',
            field=snapadmin.fields.SnapRichTextField(blank=True, null=True, verbose_name='Rich Text'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='small_int_field',
            field=snapadmin.fields.SnapSmallIntegerField(blank=True, null=True, verbose_name='Small Integer'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='file_field',
            field=snapadmin.fields.SnapFileField(blank=True, null=True, upload_to='showcase/files/', validators=[snapadmin.validators.SnapFileValidator(allowed_encodings=None, allowed_extensions=None, max_size_bytes=None), snapadmin.validators.SnapFileValidator(allowed_encodings=None, allowed_extensions=None, max_size_bytes=None)], verbose_name='File Field'),
        ),
    ]
