# Generated by Django 6.0.6 on 2026-06-23 19:52

import snapadmin.fields
import snapadmin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_showcase_color_field_showcase_phone_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', snapadmin.fields.SnapCharField(blank=True, max_length=100, verbose_name='Action')),
                ('user_email', snapadmin.fields.SnapEmailField(blank=True, max_length=254, null=True, verbose_name='User Email')),
                ('created_at', snapadmin.fields.SnapDateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
            },
        ),
        migrations.AlterField(
            model_name='showcase',
            name='color_field',
            field=snapadmin.fields.SnapColorField(blank=True, default='#3B82F6', max_length=7, null=True, validators=[snapadmin.validators.SnapColorValidator(), snapadmin.validators.SnapColorValidator()], verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='file_field',
            field=snapadmin.fields.SnapFileField(blank=True, null=True, upload_to='showcase/files/', validators=[snapadmin.validators.SnapFileValidator(allowed_encodings=None, allowed_extensions=None, max_size_bytes=None), snapadmin.validators.SnapFileValidator(allowed_encodings=None, allowed_extensions=None, max_size_bytes=None)], verbose_name='File Field'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='phone_field',
            field=snapadmin.fields.SnapPhoneField(blank=True, max_length=20, null=True, validators=[snapadmin.validators.SnapPhoneValidator(), snapadmin.validators.SnapPhoneValidator()], verbose_name='Phone Number'),
        ),
    ]
