# Generated by Django 6.0.6 on 2026-06-27 00:05

import django.db.models.deletion
import snapadmin.fields
import snapadmin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auditlog_alter_showcase_color_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='color_field',
            field=snapadmin.fields.SnapColorField(blank=True, default='#3B82F6', max_length=7, null=True, validators=[snapadmin.validators.SnapColorValidator(), snapadmin.validators.SnapColorValidator()], verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='file_field',
            field=snapadmin.fields.SnapFileField(blank=True, null=True, upload_to='showcase/files/', validators=[snapadmin.validators.SnapFileValidator(allowed_encodings=None, allowed_extensions=None, max_size_bytes=None), snapadmin.validators.SnapFileValidator(allowed_encodings=None, allowed_extensions=None, max_size_bytes=None)], verbose_name='File Field'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='phone_field',
            field=snapadmin.fields.SnapPhoneField(blank=True, max_length=20, null=True, validators=[snapadmin.validators.SnapPhoneValidator(), snapadmin.validators.SnapPhoneValidator()], verbose_name='Phone Number'),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', snapadmin.fields.SnapBooleanField(blank=True, default=False, null=True, verbose_name='Newsletter Opt-in')),
                ('bio', snapadmin.fields.SnapTextField(blank=True, null=True, verbose_name='Bio')),
                ('customer', snapadmin.fields.SnapOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='demo.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
    ]
