# Generated by Django 6.0.6 on 2026-07-04 10:04

import snapadmin.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_alter_showcase_color_field_alter_showcase_file_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', snapadmin.fields.SnapCharField(blank=False, max_length=3, null=False, unique=True, verbose_name='Currency')),
                ('base', snapadmin.fields.SnapCharField(blank=True, default='EUR', max_length=3, null=True, verbose_name='Base')),
                ('rate', snapadmin.fields.SnapDecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Rate')),
                ('synced_at', snapadmin.fields.SnapDateTimeField(auto_now=True, blank=True, null=True, verbose_name='Last Synced')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
            },
        ),
    ]
